# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OLS <- function(X, Y) {
    .Call(`_JMH_OLS`, X, Y)
}

MultVV <- function(x, y) {
    .Call(`_JMH_MultVV`, x, y)
}

MultVVoutprod <- function(x) {
    .Call(`_JMH_MultVVoutprod`, x)
}

MultVVinprod <- function(x) {
    .Call(`_JMH_MultVVinprod`, x)
}

CH <- function(H, t) {
    .Call(`_JMH_CH`, H, t)
}

HAZ <- function(H, t) {
    .Call(`_JMH_HAZ`, H, t)
}

MultMM <- function(x, y) {
    .Call(`_JMH_MultMM`, x, y)
}

haha <- function(x, y) {
    .Call(`_JMH_haha`, x, y)
}

getEC <- function(beta, tau, gamma1, gamma2, alpha1, alpha2, vee1, vee2, H01, H02, Sig, Z, X1, W, Y, X2, survtime, cmprsk, mdata, mdataS, xsmatrix, wsmatrix, CUH01, CUH02, HAZ01, HAZ02) {
    .Call(`_JMH_getEC`, beta, tau, gamma1, gamma2, alpha1, alpha2, vee1, vee2, H01, H02, Sig, Z, X1, W, Y, X2, survtime, cmprsk, mdata, mdataS, xsmatrix, wsmatrix, CUH01, CUH02, HAZ01, HAZ02)
}

getHazard <- function(CumuH01, CumuH02, survtime, cmprsk, H01, H02, CUH01, CUH02, HAZ01, HAZ02) {
    .Call(`_JMH_getHazard`, CumuH01, CumuH02, survtime, cmprsk, H01, H02, CUH01, CUH02, HAZ01, HAZ02)
}

getMC <- function(beta, tau, gamma1, gamma2, alpha1, alpha2, vee1, vee2, H01, H02, Sig, Z, X1, W, Y, X2, survtime, cmprsk, mdata, mdataS, FUNENW, FUNBENW, FUNBS, FUNBW, FUNWS, FUNBSENW, FUNEC, FUNBEC, FUNBSEC, FUNWEC, FUNWSEC, FUNB, FUNW) {
    .Call(`_JMH_getMC`, beta, tau, gamma1, gamma2, alpha1, alpha2, vee1, vee2, H01, H02, Sig, Z, X1, W, Y, X2, survtime, cmprsk, mdata, mdataS, FUNENW, FUNBENW, FUNBS, FUNBW, FUNWS, FUNBSENW, FUNEC, FUNBEC, FUNBSEC, FUNWEC, FUNWSEC, FUNB, FUNW)
}

